services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: clinica_veterinaria
    networks:
      - backend

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: server
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: clinica_veterinaria
    networks:
      - backend
      - frontend

  cliente:
    build:
      context: .
      dockerfile: cliente/Dockerfile
    container_name: cliente
    ports:
      - "4200:80"
    depends_on:
      - server
    networks:
      - frontend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
